### ISSUE TITLE
Names are hard

### ISSUE THREAD

**Issue by philj56** [scaryrawr/tofi#11]
Hey,

I've recently written and started releasing another launcher that I've been calling [tofi](https://github.com/philj56/tofi) as well, as I didn't find this when initially searching for other projects with the same name. You chose the name well before me, so I'm happy to change it. Just thought I'd ask on the off chance you wanted to relinquish the name, as there's not a lot of -ofi's left that sound good 😅.

Cool project by the way - I had to add `#include <algorithm>` in a few places to get it to build, but it works well!

**Comment by scaryrawr** [comment]
@philj56 no worries. I don't think I actually have any "rights" to the name 🤔. I can rename things here 🤣 if the worry is folks accidentally stumbling upon the repo and get confused? (cofi... kofi... 🤔). I like how we all 💖 customizing our window managers 🤣.

For the `#include <algorithm>` do you have notes on the compiler information?

Thanks!

**Comment by philj56** [comment]
Thanks so much, that's very kind! Yeah, confusion and you can't have both installed with conflicting names. I couldn't think of any other good names for mine (originally intended to be "tiny rofi" and toffee, great minds think alike :wink: ) off the top of my head (quofi, as in "quick rofi"? :stuck_out_tongue: ).
>(cofi... kofi... :thinking:)

 I thought of those two too, but they're not wholly original - [cofi](https://github.com/yandexx/cofi) already exists as a command line tool, and for kofi there's [Ko-fi](https://ko-fi.com/). For yours, the first thing that came to mind was [roti](https://en.wikipedia.org/wiki/Roti) (ro*tty*? That looks a bit too much like rotten though :slightly_frowning_face: ).

> I like how we all :sparkling_heart: customizing our window managers :rofl:.

Agreed! :grinning: 

> For the `#include <algorithm>` do you have notes on the compiler information?

Yeah sure. Using clang 14 on an up to date Arch linux, it errors basically anywhere you've used `std::transform`, `std::search` or `std::remove_if`, as those are part of `<algorithm>` (I'm not sure if that's changed in a C++ standard at some point, I'm not very up to date with C++). The full list of files seems to be
```
include/utils/popen.h
src/modes/script.cpp
src/utils/command.cpp
src/utils/posix/spawn.cpp
```
as well as `include/details/istring.hpp` in [mtl](https://github.com/scaryrawr/mtl). Just adding `#include <algorithm>` to those places makes it compile cleanly.

With g++ 12.1, I also get an error that I don't know how to fix:
```c++
/home/phil/Documents/coding/scaryrawr-tofi/src/tofi.cpp: In member function ‘void tofi::Tofi::UpdateEntries()’:
/home/phil/Documents/coding/scaryrawr-tofi/src/tofi.cpp:177:116: error: cannot capture ‘{((tofi::Tofi*)this)->tofi::Tofi::m_search.ftxui::Input::content}’ by reference
  177 |             std::stable_partition(std::begin(m_activeResults), std::end(m_activeResults), [&search{m_search.content}](const FuzzyResult &fuzzy) {
      |      
```

**Comment by scaryrawr** [comment]
Fixed algorithm bugs and renamed repo.

Thanks @philj56 !
