### ISSUE TITLE
i3wm mode brings me to first workspace automatically

### ISSUE THREAD

**Issue by biocini** [scaryrawr/tofi#9]
Hi! I was excited to try out tofi because I wanted a windowlist pretty much exactly like the app is designed. The problem is that when I invoke the i3wm mode, no matter where I instantiate tofi it immediately brings me to the first workspace. I suppose this is why you have "sticky" enabled in your example config, but is there any way to turn this default behavior off?

**Comment by biocini** [comment]
Additionally, it also appears that just selecting an option (without hitting enter) will bring the app focus to that window, which means that I have to move the cursor back to the window in order for it to work again. This makes i3wm mode unusable for me. I'm using foot terminal, if that helps

**Comment by scaryrawr** [comment]
Thanks for the feedback! I've removed the "live preview" since it sounds like it won't work in some environments. If you rebuild from the latest main I think it should be better.
